### ISSUE TITLE
Remove module?

### ISSUE THREAD

**Issue by chillu** [silverstripe-labs/spec-by-example#1]
The module has been marked as superseded by Behat for three years, and I'd be surprised if it even still works (both from the Cuke and SilverStripe sides). I propose removing it, unless we find a new maintainer in the next two weeks. Any takers?

Background: https://groups.google.com/forum/#!topic/silverstripe-dev/vgQZpUnxrI4

**Comment by tractorcow** [comment]
+1 to remove.

I've forked this personally in case anyone needs it once it's gone.

**Comment by chillu** [comment]
@tractorcow Upon further discussion with Sam, we'll probably rename `silverstripe-labs` to `silverstripe-archive` and keep the repos in there with a big fat unmaintained notice.

**Comment by tractorcow** [comment]
Good idea.

**Comment by chillu** [comment]
Marked as unmaintained in README
